name: CI/CD Workflow

on:
  workflow_call:
    inputs:
      github_token:
        required: true
        type: string
      github_actor:
        required: true
        type: string

      # Build args
      custom_tag_name:
        required: true
        type: string
      image_name:
        required: false
        type: string
      subdirectory:
        required: false
        type: string
        default: ""
      dockerfile_name:
        required: false
        type: string
        default: Dockerfile
      build_args:
        required: false
        type: string
        default: |
          _ENV=development

      # Deploy args
      ssh_enable:
        required: true
        type: string
      ssh_host:
        required: true
        type: string
      ssh_user:
        required: true
        type: string
      ssh_port:
        required: true
        type: string
      ssh_private_key:
        required: true
        type: string
      deploy_folder_path:
        required: true
        type: string
      deploy_command:
        required: true
        type: string

      # Notify args
      discord_webhook_id:
        required: true
        type: string
      discord_webhook_token:
        required: true
        type: string
      discord_enable:
        required: true
        type: string

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.git_token }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ inputs.subdirectory }}
          file: ${{ inputs.dockerfile_name }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.subdirectory != '' && inputs.subdirectory || github.event.repository.name }}:${{ inputs.custom_tag_name }}
            ${{ inputs.image_name }}
          build-args: |
            ${{ inputs.build_args }}
            GIT_TOKEN=${{ secrets.git_token }}

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Decode SSH Key
        if: ${{ inputs.ssh_enable == 'true' }}
        shell: bash
        run: |
          echo "${{ secrets.ssh_private_key }}" | base64 -d > private_key.pem
          echo "PRIVATE_KEY_PATH=private_key.pem" >> $GITHUB_ENV

      - name: Deploy Application
        if: ${{ inputs.ssh_enable == 'true' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ inputs.ssh_host }}
          username: ${{ inputs.ssh_user }}
          key_path: ${{ env.PRIVATE_KEY_PATH }}
          port: ${{ inputs.ssh_port }}
          script: |
            cd ${{ inputs.deploy_folder_path }}
            sh ${{ inputs.deploy_command }}

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Send Success Notification to Discord
        if: ${{ success() && inputs.discord_enable == 'true' }}
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ inputs.discord_webhook_id }}
          webhook_token: ${{ inputs.discord_webhook_token }}
          username: ${{ github.event.sender.login }}
          avatar_url: ${{ github.event.sender.avatar_url }}
          args: |
            ✅ **Successfully Deployed:** ${{ github.event.repository.name }}
            🔹 **Image Tag:** `${{ inputs.custom_tag_name }}`
            🔹 **Commit:** `${{ github.event.head_commit.message }}`
            🔹 **Branch:** `${{ github.ref_name }}`

      - name: Send Failure Notification to Discord
        if: ${{ failure() && inputs.discord_enable == 'true' }}
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ inputs.discord_webhook_id }}
          webhook_token: ${{ inputs.discord_webhook_token }}
          username: ${{ github.event.sender.login }}
          avatar_url: ${{ github.event.sender.avatar_url }}
          args: |
            🔴 **Failed Deployment:** ${{ github.event.repository.name }}
            ❌ **Image Tag:** `${{ inputs.custom_tag_name }}`
            ❌ **Deployment URL:** [View Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            ❌ **Commit:** `${{ github.event.head_commit.message }}`
            ❌ **Branch:** `${{ github.ref_name }}`
