name: "Send Discord Notification"

on:
  workflow_call:
    inputs:
      discord_enable:
        required: false
        type: string
        default: "true"
      discord_webhook_id:
        required: true
        type: string
      discord_webhook_token:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Success Notification to Discord
        if: ${{ success() && inputs.discord_enable == 'true' }}
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ inputs.discord_webhook_id }}
          webhook_token: ${{ inputs.discord_webhook_token }}
          username: ${{ github.event.sender.login }}
          avatar_url: ${{ github.event.sender.avatar_url }}
          args: |
            ✅ **Successfully Deployed:** ${{ github.event.repository.name }}
            🔹 **Image Tag:** `${{ inputs.image_tag }}`
            🔹 **Deployment URL:** [View Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            🔹 **Commit:** `${{ github.event.head_commit.message }}`
            🔹 **Branch:** `${{ github.ref_name }}`

      - name: Send Failure Notification to Discord
        if: ${{ failure() && inputs.discord_enable == 'true' }}
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ inputs.discord_webhook_id }}
          webhook_token: ${{ inputs.discord_webhook_token }}
          username: ${{ github.event.sender.login }}
          avatar_url: ${{ github.event.sender.avatar_url }}
          args: |
            🔴 **Failed Deployment:** ${{ github.event.repository.name }}
            ❌ **Image Tag:** `${{ inputs.image_tag }}`
            ❌ **Deployment URL:** [View Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            ❌ **Commit:** `${{ github.event.head_commit.message }}`
            ❌ **Branch:** `${{ github.ref_name }}`
