name: Docker Build and Deploy

on:
  workflow_call:  # 👈 This makes it reusable by other workflows
    inputs:
      ssh_enable:
        required: false
        type: string
        default: "true"
      ssh_host:
        required: true
        type: string
      ssh_user:
        required: true
        type: string
      ssh_private_key:
        required: true
        type: string
      ssh_port:
        required: false
        type: string
        default: "22"
      deploy_folder_path:
        required: true
        type: string
      deploy_command:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Decode SSH Key
        if: ${{ inputs.ssh_enable == 'true' }}
        shell: bash
        run: |
          decoded_key=$(echo "${{ inputs.ssh_private_key }}" | base64 -d)
          echo "DECODED_SSH_KEY<<EOF" >> $GITHUB_ENV
          echo "$decoded_key" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Deploy Application
        if: ${{ inputs.ssh_enable == 'true' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ inputs.ssh_host }}
          username: ${{ inputs.ssh_user }}
          key: ${{ env.DECODED_SSH_KEY }}
          port: ${{ inputs.ssh_port }}
          script: |
            cd ${{ inputs.deploy_folder_path }}
            sh ${{ inputs.deploy_command }}
