name: Docker Build and Deploy

on:
  workflow_call:
    inputs:
      ssh_enable:
        required: false
        type: string
        default: "true"
      ssh_host:
        required: true
        type: string
      ssh_user:
        required: true
        type: string
      ssh_private_key:
        required: true
        type: string
      ssh_port:
        required: false
        type: string
        default: "22"
      deploy_folder_path:
        required: true
        type: string
      deploy_command:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Decode SSH Key
        if: ${{ inputs.ssh_enable == 'true' }}
        id: decode_key
        run: |
          echo "${{ inputs.ssh_private_key }}" | base64 -d > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy via SSH
        if: ${{ inputs.ssh_enable == 'true' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ inputs.ssh_host }}
          username: ${{ inputs.ssh_user }}
          key: ${{ steps.decode_key.outputs.key || 'private_key.pem' }}
          port: ${{ inputs.ssh_port }}
          script: |
            cd ${{ inputs.deploy_folder_path }}
            sh ${{ inputs.deploy_command }}
